version: "3"
services:
  metrics-agent:
    build:
      context: .
    image: metrics-agent:latest
    container_name: metrics-agent
    working_dir: /app
    restart: unless-stopped
    command: [ "python", "src/main.py" ]
    user: "1001"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
      - /etc/localtime:/etc/localtime:ro # sync timezone with host machine
