[project]
name = "metrics-processor"
description = "An agent to process metrics"
dynamic = ["version"]

readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [
  { email = "matthew@davidson.engineering" },
  { name = "Matthew Davidson" },
]

classifiers = [
  "Development Status :: 1 - Planning",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Operating System :: MacOS :: MacOS X",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

dependencies = [
  "pandas>=2.2.0",
  "pyarrow>=15.0.0",
<<<<<<< HEAD
  "tomli >= 1.1.0 ; python_version < '3.11'",
  "buffered @ git+https://github.com/davidson-engineering/buffered.git@v1.0.0",
=======
  "tomli >= 2.0.1 ; python_version < '3.11'",
  "fast-database-clients @ git+https://github.com/davidson-engineering/fast-database-clients.git@v2.0.3",
  "buffered @ git+https://github.com/davidson-engineering/buffered.git@v1.0.1",
  "network-simple @ git+https://github.com/davidson-engineering/network-simple.git@v1.0.4",
  "custom-logging @ git+https://github.com/davidson-engineering/python-custom-logging.git@v1.0.2",
  "html-scraper-agent @ git+https://github.com/generalmattza/html-scraper-agent.git",
>>>>>>> 610e534d407cd43d85bef99732fc3fd49201d77d
]

# If a module, then use fetch version from src/module_name/__init__.py
[tool.setuptools.dynamic]
version = { attr = "metrics_processor.__version__" }

[project.optional-dependencies]
test = ["pytest >= 8.0.0"]

[project.urls]
homepage = "https://davidson.engineering"
repository = "https://github.com/davidson-engineering/metrics-processor"
# documentation = "https://readthedocs.org"
# changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"
