[processor]
update_interval = 1
input_buffer_length = 65_536
output_buffer_length = 65_536
batch_size = 1000

[processor.statistics]
enable_prometheus_server = false
prometheus_port = 8_000
update_interval = 60

# [server]
# buffer_length = 16384
# host = "gfyvrdatadash"
# port = 50001

# [webscraper]
# host = "10.0.0.0"
# port = 80
# update_interval = 1
