[processor]
update_interval = 1
input_buffer_length = 65_536
output_buffer_length = 65_536
batch_size = 1_000

[processor.prometheus]
enable_prometheus_server = false
prometheus_port = 8_000
update_interval = 60
