# operation:
#   operation: add
#   input1: input1
#   input2: input2
#   output: output

lower_pressure_minimum:
  operation: min
  machine: pzero
  module: sensorbox_cartridge_pressure
  operands: 
   - hornet-torr
   - stinger-torr
  result: lower_pressure-torr