# This configuration file sets acceptable boundaries for metrics.
# If a metric is outside of these boundaries, it will be removed from the data stream.
# The boundary id is set as a regular expressions (regex), and the min and max values are inclusive.
# The regex is matched against the metric id. If the id is not available, then the field name is used.
# If combine_boundaries is True in the config, then all boundaries are checked for matches and combined. 
# The order of the boundaries is important. The first boundary that matches the metric takes precedence.

.*-torr:
  max: 1000

.*-voltage:
  max: 10

.*_PID:
  max: 255

.*batterylevel:
  max: 100

.*_TC[0-9]:
  max: 150

IR.*:
  max: 150

.*-setpoint:
  max: 150

# This is a catch-all for any other metric that doesn't have a specific boundary
.*:
  min: 0